services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_api
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=development

  db:
    image: postgres:16
    container_name: postgres_mes
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mes_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: